var annotated_dup =
[
    [ "Anillo", "class_anillo.html", "class_anillo" ],
    [ "archivo", "classarchivo.html", "classarchivo" ],
    [ "ArchivoBinario", "class_archivo_binario.html", "class_archivo_binario" ],
    [ "ArchivoDeTexto", "class_archivo_de_texto.html", "class_archivo_de_texto" ],
    [ "Caballo", "class_caballo.html", "class_caballo" ],
    [ "Carta", "class_carta.html", "class_carta" ],
    [ "Circulo", "class_circulo.html", "class_circulo" ],
    [ "Cruz", "class_cruz.html", "class_cruz" ],
    [ "Cuadrado", "class_cuadrado.html", "class_cuadrado" ],
    [ "Dibujo", "class_dibujo.html", "class_dibujo" ],
    [ "Espiral", "class_espiral.html", "class_espiral" ],
    [ "Estrella", "class_estrella.html", "class_estrella" ],
    [ "Estudio", "class_estudio.html", "class_estudio" ],
    [ "Figura", "class_figura.html", "class_figura" ],
    [ "Flecha", "class_flecha.html", "class_flecha" ],
    [ "GraficadorDesempenio", "class_graficador_desempenio.html", "class_graficador_desempenio" ],
    [ "InterfazDeConsola", "class_interfaz_de_consola.html", "class_interfaz_de_consola" ],
    [ "Juego_SC", "class_juego___s_c.html", "class_juego___s_c" ],
    [ "JuegoDeLaMemoria", "class_juego_de_la_memoria.html", "class_juego_de_la_memoria" ],
    [ "Mesa", "class_mesa.html", "class_mesa" ],
    [ "Onda", "class_onda.html", "class_onda" ],
    [ "Paciente", "class_paciente.html", "class_paciente" ],
    [ "Pixel", "class_pixel.html", "class_pixel" ],
    [ "QOpenGLFunctions", "class_q_open_g_l_functions.html", null ],
    [ "QOpenGLWidget", "class_q_open_g_l_widget.html", null ],
    [ "QOpenGLWindow", "class_q_open_g_l_window.html", null ],
    [ "qt_meta_stringdata_JuegoDeLaMemoria_t", "structqt__meta__stringdata___juego_de_la_memoria__t.html", "structqt__meta__stringdata___juego_de_la_memoria__t" ],
    [ "Rectangulo", "class_rectangulo.html", "class_rectangulo" ],
    [ "Solucion", "class_solucion.html", "class_solucion" ],
    [ "SolverSaltoCaballo", "class_solver_salto_caballo.html", "class_solver_salto_caballo" ],
    [ "Tablero", "class_tablero.html", "class_tablero" ],
    [ "Tetera", "class_tetera.html", "class_tetera" ],
    [ "Texto", "class_texto.html", "class_texto" ],
    [ "Trianglo", "class_trianglo.html", "class_trianglo" ]
];